config/routes.rb
Rails.application.routes.draw do
  root :to => 'images#index'
  get '/about' => 'pages#about'

  get '/search' => 'posts#search'

  resources :users, :posts, :images
  resources :libraries, :only => [:show]
  resources :comments, :only => [:new, :create, :destroy]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/posts/:id/add_to_library' => 'libraries#add'
  # removing while browsing posts
  post '/posts/:id/remove_from_library' => 'libraries#remove'

  get '/library/posts/:id' => 'libraries#show_post'
  # removing from the library instance
  post '/library/posts/:id/remove_from_library' => 'libraries#remove_from_lib'

  post '/images/:id/add_to_library' => 'libraries#add_image'
  post '/images/:id/remove_from_library' =>  'libraries#remove_image'
  get '/library/images/:id' =>  'libraries#show_image'
  post '/library/images/:id/remove_from_library' => 'libraries#remove_image_from_lib'
end

app/models/library.rb
# == Schema Information
#
# Table name: libraries
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Library < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :posts
  has_and_belongs_to_many :images
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def show
    user = User.find @current_user.id
    @user_posts = user.posts.order(:title)
    @favourite_posts = user.library.posts.where.not(:user_id => @current_user.id).order(:title)

    @user_images = user.images
    @favourite_images = user.library.images.where.not(:user_id => @current_user.id)
  end

  def add
    post = Post.find params[:id]
    @current_user.library.posts << post
    redirect_to post_path
  end

  def remove
    lib_entry = Post.find params[:id]
    @current_user.library.posts.delete(lib_entry)
    redirect_to post_path
  end

  def remove_from_lib
    lib_entry = Post.find params[:id]
    @current_user.library.posts.delete(lib_entry)
    redirect_to library_path
  end

  def show_post
    @post = Post.find params[:id]
  end

  def add_image
    image = Image.find params[:id]
    @current_user.library.images << image
    redirect_to image_path
  end

  def remove_image
    lib_entry = Image.find params[:id]
    @current_user.library.images.delete(lib_entry)
    redirect_to image_path
  end

  def show_image
    @image = Image.find params[:id]
  end

  def remove_image_from_lib
    lib_entry = Image.find params[:id]
    @current_user.library.images.delete(lib_entry)
    redirect_to library_path
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/show.html.erb
<div class="row text-center">
  <h1><%= @current_user.name.capitalize %>'s Library</h1>
</div>

<div class="row code-label">
  <h2>Code Snippets</h2>
</div>

<div class="lib-rule"></div>

<div class="row">
  <div class="col-md-6">
    <h3>My Posts</h3>
    <% unless @user_posts.empty? %>
      <ul>
        <% @user_posts.each do |post| %>
          <li><%= link_to post.title, "/library/posts/#{ post.id }" %></li>
        <% end %>
      </ul>
    <% else %>
      <p>You haven't created any posts.</p>
      <a href="<%= new_post_path %>">Add a new post</a>
    <% end %>
  </div>
  <div class="col-md-6">
    <h3>Favourited Posts</h3>
    <% unless @favourite_posts.empty? %>
      <ul>
        <% @favourite_posts.each do |post| %>
          <li><%= link_to post.title, "/library/posts/#{ post.id }" %></li>
        <% end %>
      </ul>
    <% else %>
      <p>You haven't favourited any posts.</p>
      <a href="<%= posts_path %>">Browse posts</a>
    <% end %>
  </div>
</div>

<div class="row image-label">
  <h2>Images</h2>
</div>

<div class="lib-rule"></div>

<h3>My Images</h3>
<% unless @user_images.empty? %>
  <div class="row-custom">
    <% @user_images.each do |image| %>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <a href="<%= "/library/images/#{ image.id }" %>" class="img-responsive">
          <img src="<%= image.image_url %>" alt="">
        </a>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row">
    <p>You haven't uploaded any images.</p>
    <a href="<%= new_image_path %>">Add a new image post</a>
  </div>
<% end %>

<h3>Favourited Images</h3>

<% unless @favourite_images.empty? %>
  <div class="row-custom">
    <% @favourite_images.each do |image| %>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <a href="<%= "/library/images/#{ image.id }" %>" class="img-responsive">
          <img src="<%= image.image_url %>" alt="">
        </a>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row">
    <p>You haven't favourited any images.</p>
    <a href="<%= images_path %>">Browse images</a>
  </div>
<% end %>

app/views/libraries/show_image.html.erb
<h2><%= @image.title %></h2>

<div class="post-nav">
  <%= link_to 'Back to Library', library_path, :class => 'btn btn-default' %>
  <% if @current_user.present? && @image.user_id == @current_user.id %>
    <%= link_to 'Edit image', edit_image_path, :class => "btn btn-warning" %>
    <%= link_to 'Delete image', @image, :method => 'delete', :data => {:confirm => 'This will also remove the image from your library. Are you sure?'}, :class => "btn btn-danger" %>
  <% end %>

  <% unless @image.user_id == @current_user.id %>
    <%= link_to "/library/images/#{ @image.id }/remove_from_library", :method => :post, :class => "btn btn-danger" do %>
        <i class="glyphicon glyphicon-minus"></i> Remove from Library
      <% end %>
  <% end %>
</div>

<% @author = User.find(@image.user_id) %>
<p>Posted by: <a href="<%= "/users/#{@image.user_id}" %>"><%= @author.name.capitalize %></a></p>

<p>Source: <%= @image.source %></p>

<img src="<%= @image.image_url %>" alt="">

<div class="panel panel-default lib-show-image-panel">
  <div class="panel-heading">
    <h3 class="panel-title">Description</h3>
  </div>
  <div class="panel-body">
      <p><%= @image.description %></p>
  </div>
</div>

app/views/libraries/show_post.html.erb
<h2><%= @post.title %></h2>

<div class="post-nav">
  <%= link_to 'Back to Library', library_path, :class => 'btn btn-default' %>
  <% if @current_user.present? && @post.user_id == @current_user.id %>
    <%= link_to 'Edit post', edit_post_path, :class => "btn btn-warning" %>
    <%= link_to 'Delete post', @post, :method => 'delete', :data => {:confirm => 'This will also remove the post from your library. Are you sure?'}, :class => "btn btn-danger" %>
  <% end %>

  <% unless @post.user_id == @current_user.id %>
    <%= link_to "/library/posts/#{ @post.id }/remove_from_library", :method => :post, :class => "btn btn-danger" do %>
        <i class="glyphicon glyphicon-minus"></i> Remove from Library
      <% end %>
  <% end %>
</div>

<% @author = User.find(@post.user_id) %>
<p>Posted by: <a href="<%= "/users/#{@post.user_id}" %>"><%= @author.name.capitalize %></a></p>

<iframe height='350' scrolling='no' src='<%= @post.codepen_embed %>' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'></iframe>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Description</h3>
  </div>
  <div class="panel-body">
      <p><%= @post.description %></p>
  </div>
</div>