code_stock_app/config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :users, :posts
  # change below to only certain resources (e.g. can't delete a library)
  resources :libraries

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/posts/:id/add_to_library' => 'libraries#add'
  # removing while browsing posts
  post '/posts/:id/remove_from_library' => 'libraries#remove'

  get '/library/posts/:id' => 'libraries#show_post'
  # removing from the library instance
  post '/library/posts/:id/remove_from_library' => 'libraries#remove_from_lib'
end

code_stock_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

code_stock_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeStock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>

          <!-- if nobody is signed in -->
          <% unless @current_user.present? %>
            <li><%= link_to 'Sign up', new_user_path %></li>
            <li><%= link_to 'Log in', login_path %></li>
          <% end %>

          <!-- if a user is signed in -->
          <% if  @current_user.present? %>

            <!-- check if admin -->
            <% if @current_user.is_admin? %>
              <li><%= link_to 'All users', users_path %></li>
            <% end %>

            <li><a href="/users/<%= @current_user.id %>">My Profile</a></li>
            <li><%= link_to 'Sign out ' + @current_user.name, login_path, :method => :delete %></li>
            <li><%= link_to 'Create a new post', new_post_path %></li>
            <li><%= link_to 'My Library', "/libraries/#{ @current_user.id }" %></li>
          <% end %>
          <li><%= link_to 'View posts', posts_path %></li>
        </ul>
    </div>
  </nav>


  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

code_stock_app/app/views/pages/home.html.erb
<h1>This is the homepage.</h1>

<h2>'Completed' features:</h2>

<h3>Authentication</h3>
<ul>
  <li>sign up</li>
  <li>log in</li>
  <li>log out</li>
  <li>automatic login upon signing up</li>
  <li>hardcoded admin user</li>
  <li>admin can view everyone's profile</li>
</ul>

<h3>User Stuff</h3>
<ul>
  <li>present error messages when user is an idiot</li>
  <li>relationships seem to be set up and working (on pry)</li>
  <li>make profile page and links to it</li>
  <li>add some seed data with dummy content and images to play around with and test profile pages</li>
  <li>add in a link to a form, so a user can edit their profile, allowing them to add a bio and image etc.</li>
</ul>

<h3>Post Stuff</h3>
<ul>
  <li>posting system works for adding and reading a post, as well as listing on the index page</li>
  <li>make a link for a new post for users that are signed in (you can view posts without an account, but need one to post and have a lib)</li>
  <li>post is given a user_id upon creation, relating it to the author of the post</li>
  <li>translated the author id into a name</li>
  <li>need to be able to update/edit and delete posts</li>
  <li>crUD system for posts, only author can edit/delete their own post</li>
  <li>when user inputs a codepen url in post creation, pen appears on the post page</li>
</ul>

<h3>Library stuff</h3>
<ul>
  <li>figured out how to give a user a library object automatically when they sign up (so they can view it and add to it)</li>
  <li>new posts are automatically added to the author's library</li>
  <li>make a view library page specific to the current user</li>
  <li>add to library function</li>
  <li>hide the add library option if the current user already has it in their library</li>
  <li>replaced the add to lib with a remove from library function for the current user if it's already in there</li>
  <li>added a like/pin/add to library link on every post only if user is logged in</li>
  <li><b>managed to sort out differentiation between removing from lib while browsing post index and removing from lib while in lib. Both need to redirect to different places. When removing from lib you need to be redirected to your lib index, when browsing and removing you need to be redirected to the index of all posts. Done!</b></li>
</ul>

<h2>To do</h2>
<h3>Next steps</h3>
<ul>
  <li>add a 'back' page to posts to go back to the relevant index page (posts/library) because going back in browser doesn't work</li>
  <li>come up with a solution to the image problem for a post. Need to somehow get a sort of preview from the embed</li>
  <li>mess around with codepen embed to make it better, but keep it working</li>
  <li>try and break shit and fix if necessary</li>
</ul>

<h3>Low Priority</h3>
<ul>
  <li>put in an added to library message when the users adds a post to their lib</li>
  <li>sort out the nav mess in the layout erb</li>
  <li>sort out the ordering of the nav bar on the actual page</li>
  <li>display posts in a sexy grid</li>

  <li>get a search function going for site content</li>
  <li>give admin power to see post list and delete any inappropriate one, e.g. CSS penis</li>
</ul>