config/routes.rb
Rails.application.routes.draw do
  root :to => 'images#index'
  get '/about' => 'pages#about'

  get '/search' => 'posts#search'

  resources :users, :posts, :images
  resources :libraries, :only => [:show]
  resources :comments, :only => [:new, :create, :destroy]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/posts/:id/add_to_library' => 'libraries#add'
  # removing while browsing posts
  post '/posts/:id/remove_from_library' => 'libraries#remove'

  get '/library/posts/:id' => 'libraries#show_post'
  # removing from the library instance
  post '/library/posts/:id/remove_from_library' => 'libraries#remove_from_lib'

  post '/images/:id/add_to_library' => 'libraries#add_image'
  post '/images/:id/remove_from_library' =>  'libraries#remove_image'
  get '/library/images/:id' =>  'libraries#show_image'
  post '/library/images/:id/remove_from_library' => 'libraries#remove_image_from_lib'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :integer          not null, primary key
#  title         :string
#  description   :text
#  image         :text
#  codepen       :text
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  codepen_embed :text
#  blurb         :text
#

class Post < ActiveRecord::Base
  has_and_belongs_to_many :libraries
  belongs_to :user
  has_many :comments

  def self.search(query)
    where("title ilike ?", "%#{query}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(:title)
  end

  def search
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find params[:id]
    @comment = Comment.new
  end

  def create
    @post = Post.create post_params

    if @post.save
      @post.update(:user_id => @current_user.id)
      @current_user.library.posts << @post

      x = @post.codepen.gsub("/pen", "/embed").gsub("http", "https")

      @post.update(:codepen_embed => x)
      redirect_to "/library/posts/#{ @post.id }"
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    post = Post.find params[:id]
    post.update post_params
    redirect_to "/library/posts/#{ post.id }"
  end

  def destroy
    post = Post.find params[:id]
    post.destroy

    if @current_user.is_admin?
      redirect_to posts_path
    else
      redirect_to library_path
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :codepen, :description, :blurb)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_for @comment, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%= f.text_area :text, :class => "form-control comment-textbox", :placeholder => "Write a comment" %>
    </div>
  </div>

  <%= f.hidden_field :post_page_id, :value => @post.id %>

  <div class="form-group">
    <div class="col-md-offset-3 col-md-6">
      <%= f.submit 'Post', :class => "btn btn-signin" %>
    </div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :autofocus => true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :codepen %>
    <%= f.text_field :codepen, :required => true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.submit "Post snippet", :class => "btn btn-signin" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="formbox animated pulse">
  <h2>Edit Code Snippet</h2>
  <%= render :partial => 'form' %>
</div>

app/views/posts/index.html.erb
<div class="text-right">
  <div class="col-md-3 col-md-offset-9">
    <%= form_tag("/search", :method => "get", id: "search-form") do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts", :class => "form-control" %>
        <span class="input-group-btn">
          <button class="btn btn-default" type="button"><i class="glyphicon glyphicon-search"></i></button>
        </span>
      </div>
    <% end %>
  </div>
</div>

<h1 class="text-center animated fadeInLeftBig">Code Snippets</h1>

<div class="col-md-6 col-md-offset-3 animated fadeInLeft">
  <ul class="list-group">
    <% @posts.each do |post| %>
    <% @author = User.find(post.user_id) %>
      <li class="list-group-item"><%= link_to post.title, "/posts/#{ post.id }" %> - posted by <%= @author.name.capitalize %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<div class="formbox animated pulse">
  <h2>New Code Snippet</h2>
  <%= render :partial => 'form' %>
</div>

app/views/posts/search.html.erb
<div class="text-right">
  <div class="col-md-3 col-md-offset-9">
    <%= form_tag("/search", :method => "get", id: "search-form") do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts", :class => "form-control" %>
        <span class="input-group-btn">
          <button class="btn btn-default" type="button"><i class="glyphicon glyphicon-search"></i></button>
        </span>
      </div>
    <% end %>
  </div>
</div>

<h2>Search Results:</h2>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, "/posts/#{ post.id }" %></li>
  <% end %>
</ul>

<% if @posts.length == 0 %>
  <div class="alert alert-danger" role="alert">
    <p>Sorry, there are no results. Please try again.</p>
  </div>
<% end %>

<%= link_to 'Back to posts', posts_path, :class => 'btn btn-signin search-back' %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<% @author = User.find(@post.user_id) %>
<p>Posted by: <a href="<%= "/users/#{@post.user_id}" %>"><%= @author.name.capitalize %></a></p>

<div class="post-nav">
  <%= link_to 'Back to posts', posts_path, :class => 'btn btn-default' %>
  <% if @current_user.present? && (@post.user_id != @current_user.id) %>
    <% unless @current_user.library.posts.include? @post %>
      <%= link_to "/posts/#{ @post.id }/add_to_library", :method => :post, :class => "btn btn-success" do %>
          <i class="glyphicon glyphicon-plus"></i> Add to Library
      <% end %>
    <% else %>
      <%= link_to "/posts/#{ @post.id }/remove_from_library", :method => :post, :class => "btn btn-danger" do %>
        <i class="glyphicon glyphicon-minus"></i> Remove from Library
      <% end %>
    <% end %>
  <% end %>

  <% unless @current_user == nil %>
    <% if @current_user.is_admin? %>
      <%= link_to 'Delete post', @post, :method => 'delete', :data => {:confirm => 'Are you sure, admin?'}, :class => "btn btn-danger" %>
    <% end %>
  <% end %>
</div>

<iframe height='350' scrolling='no' src='<%= @post.codepen_embed %>' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'></iframe>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Description</h3>
  </div>
  <div class="panel-body">
      <p><%= @post.description %></p>
  </div>
</div>

<% if @current_user.present? %>
  <div class="col-md-6 col-md-offset-3">
    <h2>Comments</h2>
  </div>
<% end %>

<div class="container">
  <% @post.comments.each do |comment| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 comment-box">
          <p><a href="<%= "/users/#{comment.user_id}" %>"><%= comment.user.name.capitalize %></a><%= comment.created_at.strftime(" - posted on %m/%d/%Y") %><%= comment.created_at.strftime(" at %I:%M%p")   %></p>
          <p>
            <%= comment.text %>
          </p>
          <% if @current_user != nil && (@current_user.is_admin? || @current_user.id == comment.user_id) %>
            <%= link_to 'Delete', comment_path, :method => :delete, :data => {:confirm => 'Are you sure?'} %>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if @current_user.present? %>
  <%= render :partial => 'comment_form' %>
<% end %>