config/routes.rb
Rails.application.routes.draw do
  root :to => 'images#index'
  get '/about' => 'pages#about'

  get '/search' => 'posts#search'

  resources :users, :posts, :images
  resources :libraries, :only => [:show]
  resources :comments, :only => [:new, :create, :destroy]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/posts/:id/add_to_library' => 'libraries#add'
  # removing while browsing posts
  post '/posts/:id/remove_from_library' => 'libraries#remove'

  get '/library/posts/:id' => 'libraries#show_post'
  # removing from the library instance
  post '/library/posts/:id/remove_from_library' => 'libraries#remove_from_lib'

  post '/images/:id/add_to_library' => 'libraries#add_image'
  post '/images/:id/remove_from_library' =>  'libraries#remove_image'
  get '/library/images/:id' =>  'libraries#show_image'
  post '/library/images/:id/remove_from_library' => 'libraries#remove_image_from_lib'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snip{it}</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/assets/font-awesome.min.css">
</head>
<body>
  <nav class="navbar navbar-default header-nav">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><a href="<%= posts_path %>">&lt;&#47;&gt;</a></li>
        <li><a href="<%= images_path %>"><span class="glyphicon glyphicon-picture"></span></a></li>
        <% if  @current_user.present? && @current_user.is_admin? %>
          <li><a href="<%= users_path %>"><span class="glyphicon glyphicon-user"></span></a></li>
        <% end %>
        <a class="navbar-brand" href="<%= root_path %>"><span class="snip">snip</span><span class="braces">{</span><span class="it">it</span><span class="braces">}</span></a>
      </ul>

      <% if @current_user == nil %>
        <%= render :partial => '/session/new' %>
      <% else %>
        <div class="btn-group navbar-right user-dropdown" role="group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= @current_user.name.capitalize %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/users/<%= @current_user.id %>"><span class="glyphicon glyphicon-user"></span>  My Profile</a></li>
            <li><a href="<%= "/libraries/#{ @current_user.id }" %>"><span class="glyphicon glyphicon-book"></span>  My Library</a></li>
            <li class="divider"></li>
            <li><%= link_to '+ Add Snippet', new_post_path %></li>
            <li><%= link_to '+ Add Image', new_image_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign Out ' + @current_user.name.capitalize, login_path, :method => :delete %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>

  <div class="container main-content">
    <%= yield %>
  </div>

  <div id="footer" class="text-center">
    <div class="container-fluid">
      <p>
        <%= link_to 'About', about_path %>
      </p>
      <p>&copy; 2015 Tom Valorsa</p>
    </div>
  </div>
</body>
</html>